-- ============================================================
-- LaFibre CRM - Supabase 完整初始化脚本
-- 合并自 migrations/01~16, rls.sql, seed.sql
-- 从 MySQL (Directus CMS) 迁移到 Supabase (PostgreSQL)
-- ============================================================

-- ============================================================
-- 1. 扩展
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 2. profiles 用户表
-- ============================================================
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text,
  email text UNIQUE,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_select_authenticated" ON public.profiles
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_insert_authenticated" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "profiles_update_authenticated" ON public.profiles
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "profiles_delete_authenticated" ON public.profiles
  FOR DELETE TO authenticated USING (true);

-- ============================================================
-- 3. classify 分类表
-- ============================================================
CREATE TABLE public.classify (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text
);
ALTER TABLE public.classify ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 4. tag_color 颜色标签表
-- ============================================================
CREATE TABLE public.tag_color (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.tag_color ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 5. tag_shazhi 纱质标签表
-- ============================================================
CREATE TABLE public.tag_shazhi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.tag_shazhi ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 6. sku 面料SKU表
-- ============================================================
CREATE TABLE public.sku (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  code text,
  brand text,
  name text,
  cover uuid,
  remark text,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.sku ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 7. sku_classify_price SKU分类价格表
-- ============================================================
CREATE TABLE public.sku_classify_price (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  sku_id bigint REFERENCES public.sku(id) ON DELETE SET NULL,
  classify_id bigint REFERENCES public.classify(id) ON DELETE SET NULL,
  price integer
);
ALTER TABLE public.sku_classify_price ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 8. customer 客户表
-- ============================================================
CREATE TABLE public.customer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text,
  phone text,
  remark text,
  wedding_date date,
  address text
);
ALTER TABLE public.customer ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 9. appointment 预约表
-- ============================================================
CREATE TABLE public.appointment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  event text NOT NULL DEFAULT '其他',
  remark text,
  counselor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  start_time timestamptz,
  end_time timestamptz,
  customer_id bigint REFERENCES public.customer(id) ON DELETE SET NULL,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.appointment ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 10. "order" 订单表 (保留原表名，需双引号)
-- ============================================================
CREATE TABLE public."order" (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  pay_type text,
  remark text,
  real_price numeric(10,2),
  total_price numeric(10,2),
  customer_id bigint REFERENCES public.customer(id) ON DELETE SET NULL,
  customer_name text,
  counselor_name text
);
ALTER TABLE public."order" ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 11. order_payment 订单付款表
-- ============================================================
CREATE TABLE public.order_payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz NOT NULL DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  price numeric(10,2),
  show_counselor_name text
);
ALTER TABLE public.order_payment ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 12. order_progress 订单进度表
-- ============================================================
CREATE TABLE public.order_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  mianliao_price numeric(10,5),
  maopi_daohuo_time date,
  xizhuang_xiadan_time date,
  fanchang_time date,
  chengyi_daohuo_time date,
  gongyi_price numeric(10,5),
  chenshan_mianliao_xiadan_time date,
  chenshan_mianliao_price numeric(10,5),
  chenshan_changjia text,
  chenshan_xiadan_time date,
  chenshan_daohuo_time date,
  chenshan_gongyi_price integer,
  peijian_xiadan_time date,
  peijian_daohuo_time date,
  peijian_price text,
  xizhuang_mianliao text,
  xizhuang_mianliao_bianhao text,
  mianliao_xiadan_time timestamptz,
  xizhuang_changjia text,
  chenshan_mianliao_bianhao text,
  peijian_bianhao text,
  quyi_time timestamptz,
  quyi_content text,
  beizhu text,
  maopi_daohuo_time2 date,
  guke_name text
);
ALTER TABLE public.order_progress ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 13. order_sku_detail 订单SKU明细表
-- ============================================================
CREATE TABLE public.order_sku_detail (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  classify_id bigint REFERENCES public.classify(id) ON DELETE SET NULL,
  color_id bigint REFERENCES public.tag_color(id) ON DELETE SET NULL,
  shazhi_id bigint REFERENCES public.tag_shazhi(id) ON DELETE SET NULL,
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  sku_id bigint REFERENCES public.sku(id) ON DELETE SET NULL,
  price numeric(10,5),
  mianliao_bianhao text
);
ALTER TABLE public.order_sku_detail ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 14. 索引
-- ============================================================
CREATE INDEX idx_classify_user_created ON public.classify(user_created);
CREATE INDEX idx_classify_user_updated ON public.classify(user_updated);

CREATE INDEX idx_tag_color_user_created ON public.tag_color(user_created);
CREATE INDEX idx_tag_color_user_updated ON public.tag_color(user_updated);

CREATE INDEX idx_tag_shazhi_user_created ON public.tag_shazhi(user_created);
CREATE INDEX idx_tag_shazhi_user_updated ON public.tag_shazhi(user_updated);

CREATE INDEX idx_sku_user_created ON public.sku(user_created);
CREATE INDEX idx_sku_user_updated ON public.sku(user_updated);

CREATE INDEX idx_sku_classify_price_sku ON public.sku_classify_price(sku_id);
CREATE INDEX idx_sku_classify_price_classify ON public.sku_classify_price(classify_id);

CREATE INDEX idx_customer_user_created ON public.customer(user_created);
CREATE INDEX idx_customer_user_updated ON public.customer(user_updated);

CREATE INDEX idx_appointment_counselor ON public.appointment(counselor_id);
CREATE INDEX idx_appointment_customer ON public.appointment(customer_id);
CREATE INDEX idx_appointment_user_created ON public.appointment(user_created);

CREATE INDEX idx_order_user_id ON public."order"(user_id);
CREATE INDEX idx_order_customer_id ON public."order"(customer_id);
CREATE INDEX idx_order_user_created ON public."order"(user_created);

CREATE INDEX idx_order_payment_order_id ON public.order_payment(order_id);

CREATE INDEX idx_order_progress_order_id ON public.order_progress(order_id);

CREATE INDEX idx_order_sku_detail_order_id ON public.order_sku_detail(order_id);
CREATE INDEX idx_order_sku_detail_sku_id ON public.order_sku_detail(sku_id);
CREATE INDEX idx_order_sku_detail_classify_id ON public.order_sku_detail(classify_id);
CREATE INDEX idx_order_sku_detail_color_id ON public.order_sku_detail(color_id);
CREATE INDEX idx_order_sku_detail_shazhi_id ON public.order_sku_detail(shazhi_id);

-- ============================================================
-- 15. 触发器函数
-- ============================================================
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, status)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data->>'name',
      NEW.raw_user_meta_data->>'display_name',
      NEW.raw_user_meta_data->>'full_name',
      NEW.raw_user_meta_data->>'first_name'
    ),
    NEW.email,
    'active'
  );
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_user_created()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- 只在未传入 user_created 时才从 auth.uid() 填入
  IF NEW.user_created IS NULL THEN
    NEW.user_created = auth.uid();
  END IF;
  -- 只在未传入 date_created 时才填入当前时间（保留迁移数据的原始时间）
  IF NEW.date_created IS NULL THEN
    NEW.date_created = now();
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_user_updated()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  -- 只在未传入 user_updated 时才从 auth.uid() 填入
  IF NEW.user_updated IS NULL THEN
    NEW.user_updated = auth.uid();
  END IF;
  -- 只在未传入 date_updated 时才填入当前时间（保留迁移数据的原始时间）
  IF NEW.date_updated IS NULL THEN
    NEW.date_updated = now();
  END IF;
  RETURN NEW;
END;
$$;

-- ============================================================
-- 16. 触发器
-- ============================================================
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER set_classify_user_created
  BEFORE INSERT ON public.classify
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_classify_user_updated
  BEFORE UPDATE ON public.classify
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_tag_color_user_created
  BEFORE INSERT ON public.tag_color
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_tag_color_user_updated
  BEFORE UPDATE ON public.tag_color
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_tag_shazhi_user_created
  BEFORE INSERT ON public.tag_shazhi
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_tag_shazhi_user_updated
  BEFORE UPDATE ON public.tag_shazhi
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_sku_user_created
  BEFORE INSERT ON public.sku
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_sku_user_updated
  BEFORE UPDATE ON public.sku
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_sku_classify_price_user_created
  BEFORE INSERT ON public.sku_classify_price
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_sku_classify_price_user_updated
  BEFORE UPDATE ON public.sku_classify_price
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_customer_user_created
  BEFORE INSERT ON public.customer
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_customer_user_updated
  BEFORE UPDATE ON public.customer
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_appointment_user_created
  BEFORE INSERT ON public.appointment
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_appointment_user_updated
  BEFORE UPDATE ON public.appointment
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_order_user_created
  BEFORE INSERT ON public."order"
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_order_user_updated
  BEFORE UPDATE ON public."order"
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_order_payment_user_created
  BEFORE INSERT ON public.order_payment
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_order_payment_user_updated
  BEFORE UPDATE ON public.order_payment
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_order_progress_user_created
  BEFORE INSERT ON public.order_progress
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_order_progress_user_updated
  BEFORE UPDATE ON public.order_progress
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

CREATE TRIGGER set_order_sku_detail_user_created
  BEFORE INSERT ON public.order_sku_detail
  FOR EACH ROW EXECUTE FUNCTION public.set_user_created();
CREATE TRIGGER set_order_sku_detail_user_updated
  BEFORE UPDATE ON public.order_sku_detail
  FOR EACH ROW EXECUTE FUNCTION public.set_user_updated();

-- ============================================================
-- 17. RLS 策略 - classify
-- ============================================================
CREATE POLICY "classify_select_authenticated" ON public.classify
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "classify_insert_authenticated" ON public.classify
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "classify_update_authenticated" ON public.classify
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "classify_delete_authenticated" ON public.classify
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - tag_color
CREATE POLICY "tag_color_select_authenticated" ON public.tag_color
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "tag_color_insert_authenticated" ON public.tag_color
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "tag_color_update_authenticated" ON public.tag_color
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "tag_color_delete_authenticated" ON public.tag_color
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - tag_shazhi
CREATE POLICY "tag_shazhi_select_authenticated" ON public.tag_shazhi
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "tag_shazhi_insert_authenticated" ON public.tag_shazhi
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "tag_shazhi_update_authenticated" ON public.tag_shazhi
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "tag_shazhi_delete_authenticated" ON public.tag_shazhi
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - sku
CREATE POLICY "sku_select_authenticated" ON public.sku
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "sku_insert_authenticated" ON public.sku
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "sku_update_authenticated" ON public.sku
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "sku_delete_authenticated" ON public.sku
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - sku_classify_price
CREATE POLICY "sku_classify_price_select_authenticated" ON public.sku_classify_price
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "sku_classify_price_insert_authenticated" ON public.sku_classify_price
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "sku_classify_price_update_authenticated" ON public.sku_classify_price
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "sku_classify_price_delete_authenticated" ON public.sku_classify_price
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - customer
CREATE POLICY "customer_select_authenticated" ON public.customer
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "customer_insert_authenticated" ON public.customer
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "customer_update_authenticated" ON public.customer
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "customer_delete_authenticated" ON public.customer
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - appointment
CREATE POLICY "appointment_select_authenticated" ON public.appointment
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "appointment_insert_authenticated" ON public.appointment
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "appointment_update_authenticated" ON public.appointment
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "appointment_delete_authenticated" ON public.appointment
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - order
CREATE POLICY "order_select_authenticated" ON public."order"
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "order_insert_authenticated" ON public."order"
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "order_update_authenticated" ON public."order"
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "order_delete_authenticated" ON public."order"
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - order_payment
CREATE POLICY "order_payment_select_authenticated" ON public.order_payment
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "order_payment_insert_authenticated" ON public.order_payment
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "order_payment_update_authenticated" ON public.order_payment
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "order_payment_delete_authenticated" ON public.order_payment
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - order_progress
CREATE POLICY "order_progress_select_authenticated" ON public.order_progress
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "order_progress_insert_authenticated" ON public.order_progress
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "order_progress_update_authenticated" ON public.order_progress
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "order_progress_delete_authenticated" ON public.order_progress
  FOR DELETE TO authenticated USING (true);

-- RLS 策略 - order_sku_detail
CREATE POLICY "order_sku_detail_select_authenticated" ON public.order_sku_detail
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "order_sku_detail_insert_authenticated" ON public.order_sku_detail
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "order_sku_detail_update_authenticated" ON public.order_sku_detail
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "order_sku_detail_delete_authenticated" ON public.order_sku_detail
  FOR DELETE TO authenticated USING (true);

-- ============================================================
-- 18. 种子数据
-- ============================================================
INSERT INTO public.classify (id, name) VALUES
  (1, '两件套'),
  (2, '三件套'),
  (3, '西服'),
  (4, '裤子'),
  (5, '马甲'),
  (7, '衬衫'),
  (8, '袖扣'),
  (9, '领结'),
  (10, '领带'),
  (11, '皮鞋'),
  (12, '活动'),
  (13, '30000充值卡'),
  (14, '里布'),
  (15, 'POLO')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tag_color (id, name) VALUES
  (1, '黑'),
  (2, '灰'),
  (3, '白'),
  (4, '红'),
  (5, '蓝'),
  (6, '香槟色')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tag_shazhi (id, name) VALUES
  (1, '60''s'),
  (2, '100''s'),
  (3, '110''s'),
  (4, '120''s'),
  (5, '130''s'),
  (6, '140''s'),
  (7, '150''s'),
  (8, '160''s')
ON CONFLICT (id) DO NOTHING;

SELECT setval('public.classify_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.classify));
SELECT setval('public.tag_color_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.tag_color));
SELECT setval('public.tag_shazhi_id_seq', (SELECT COALESCE(MAX(id), 0) + 1 FROM public.tag_shazhi));
