-- ============================================================
-- LaFibre CRM - Supabase 数据库初始化 (合并版)
-- 从 MySQL (Directus CMS) 迁移到 Supabase (PostgreSQL)
--
-- ⚠️ 如果在 Supabase SQL Editor 中执行报错，请使用
--    migrations/ 目录下的拆分文件，按编号顺序逐个执行
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- profiles
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name text,
  email text UNIQUE,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select_authenticated" ON public.profiles
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_insert_authenticated" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "profiles_update_authenticated" ON public.profiles
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "profiles_delete_authenticated" ON public.profiles
  FOR DELETE TO authenticated USING (true);

-- classify
CREATE TABLE public.classify (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text
);
ALTER TABLE public.classify ENABLE ROW LEVEL SECURITY;

-- tag_color
CREATE TABLE public.tag_color (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.tag_color ENABLE ROW LEVEL SECURITY;

-- tag_shazhi
CREATE TABLE public.tag_shazhi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.tag_shazhi ENABLE ROW LEVEL SECURITY;

-- sku
CREATE TABLE public.sku (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  code text,
  name text,
  cover uuid,
  remark text,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.sku ENABLE ROW LEVEL SECURITY;

-- sku_classify_price
CREATE TABLE public.sku_classify_price (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  sku_id bigint REFERENCES public.sku(id) ON DELETE SET NULL,
  classify_id bigint REFERENCES public.classify(id) ON DELETE SET NULL,
  price integer
);
ALTER TABLE public.sku_classify_price ENABLE ROW LEVEL SECURITY;

-- customer
CREATE TABLE public.customer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  name text,
  phone text,
  remark text,
  wedding_date date,
  address text
);
ALTER TABLE public.customer ENABLE ROW LEVEL SECURITY;

-- appointment
CREATE TABLE public.appointment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  event text NOT NULL DEFAULT '其他',
  remark text,
  counselor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  start_time timestamptz,
  end_time timestamptz,
  customer_id bigint REFERENCES public.customer(id) ON DELETE SET NULL,
  archived boolean NOT NULL DEFAULT false
);
ALTER TABLE public.appointment ENABLE ROW LEVEL SECURITY;

-- "order" (保留原表名，需双引号)
CREATE TABLE public."order" (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  pay_type text,
  remark text,
  real_price numeric(10,2),
  total_price numeric(10,2),
  customer_id bigint REFERENCES public.customer(id) ON DELETE SET NULL,
  customer_name text,
  counselor_name text
);
ALTER TABLE public."order" ENABLE ROW LEVEL SECURITY;

-- order_payment
CREATE TABLE public.order_payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz NOT NULL DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  price numeric(10,2),
  show_counselor_name text
);
ALTER TABLE public.order_payment ENABLE ROW LEVEL SECURITY;

-- order_progress
CREATE TABLE public.order_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  mianliao_price numeric(10,5),
  maopi_daohuo_time date,
  xizhuang_xiadan_time date,
  fanchang_time date,
  chengyi_daohuo_time date,
  gongyi_price numeric(10,5),
  chenshan_mianliao_xiadan_time date,
  chenshan_mianliao_price numeric(10,5),
  chenshan_changjia text,
  chenshan_xiadan_time date,
  chenshan_daohuo_time date,
  chenshan_gongyi_price integer,
  peijian_xiadan_time date,
  peijian_daohuo_time date,
  peijian_price text,
  xizhuang_mianliao text,
  xizhuang_mianliao_bianhao text,
  mianliao_xiadan_time timestamptz,
  xizhuang_changjia text,
  chenshan_mianliao_bianhao text,
  peijian_bianhao text,
  quyi_time timestamptz,
  quyi_content text,
  beizhu text,
  maopi_daohuo_time2 date,
  guke_name text
);
ALTER TABLE public.order_progress ENABLE ROW LEVEL SECURITY;

-- order_sku_detail
CREATE TABLE public.order_sku_detail (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_created timestamptz DEFAULT now(),
  user_updated uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date_updated timestamptz DEFAULT now(),
  classify_id bigint REFERENCES public.classify(id) ON DELETE SET NULL,
  color_id bigint REFERENCES public.tag_color(id) ON DELETE SET NULL,
  shazhi_id bigint REFERENCES public.tag_shazhi(id) ON DELETE SET NULL,
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  sku_id bigint REFERENCES public.sku(id) ON DELETE SET NULL,
  price numeric(10,5),
  mianliao_bianhao text
);
ALTER TABLE public.order_sku_detail ENABLE ROW LEVEL SECURITY;
