-- Step 3: 创建基础字典表 (classify, tag_color, tag_shazhi)

CREATE TABLE public.classify (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  name text
);

ALTER TABLE public.classify ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.tag_color (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  name text
);

ALTER TABLE public.tag_color ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.tag_shazhi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  name text
);

ALTER TABLE public.tag_shazhi ENABLE ROW LEVEL SECURITY;
