-- Step 4: 创建 SKU 相关表

CREATE TABLE public.sku (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  code text,
  name text,
  cover uuid
);

ALTER TABLE public.sku ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.sku_classify_price (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  sku_id bigint REFERENCES public.sku(id) ON DELETE SET NULL,
  classify_id bigint REFERENCES public.classify(id) ON DELETE SET NULL,
  price integer
);

ALTER TABLE public.sku_classify_price ENABLE ROW LEVEL SECURITY;
