-- Step 5: 创建客户和预约表

CREATE TABLE public.customer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  name text,
  phone text,
  remark text,
  wedding_date date,
  address text
);

ALTER TABLE public.customer ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.appointment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort integer,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  event text NOT NULL DEFAULT '其他',
  remark text,
  counselor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  start_time timestamptz,
  end_time timestamptz,
  customer_id bigint REFERENCES public.customer(id) ON DELETE SET NULL,
  archived boolean NOT NULL DEFAULT false
);

ALTER TABLE public.appointment ENABLE ROW LEVEL SECURITY;
