-- Step 6: 创建订单相关表

CREATE TABLE public."order" (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  pay_type text,
  remark text,
  real_price numeric(10,2),
  total_price numeric(10,2),
  customer_id bigint REFERENCES public.customer(id) ON DELETE SET NULL,
  customer_name text,
  counselor_name text
);

ALTER TABLE public."order" ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.order_payment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz NOT NULL DEFAULT now(),
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  price numeric(10,2),
  show_counselor_name text
);

ALTER TABLE public.order_payment ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.order_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  mianliao_price numeric(10,5),
  maopi_daohuo_time date,
  xizhuang_xiadan_time date,
  fanchang_time date,
  chengyi_daohuo_time date,
  gongyi_price numeric(10,5),
  chenshan_mianliao_xiadan_time date,
  chenshan_mianliao_price numeric(10,5),
  chenshan_changjia text,
  chenshan_xiadan_time date,
  chenshan_daohuo_time date,
  chenshan_gongyi_price integer,
  peijian_xiadan_time date,
  peijian_daohuo_time date,
  peijian_price text,
  xizhuang_mianliao text,
  xizhuang_mianliao_bianhao text,
  mianliao_xiadan_time timestamptz,
  xizhuang_changjia text,
  chenshan_mianliao_bianhao text,
  peijian_bianhao text,
  quyi_time timestamptz,
  quyi_content text,
  beizhu text,
  maopi_daohuo_time2 date,
  guke_name text
);

ALTER TABLE public.order_progress ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.order_sku_detail (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_created uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_created timestamptz,
  user_updated uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  date_updated timestamptz,
  classify_id bigint REFERENCES public.classify(id) ON DELETE SET NULL,
  color_id bigint REFERENCES public.tag_color(id) ON DELETE SET NULL,
  shazhi_id bigint REFERENCES public.tag_shazhi(id) ON DELETE SET NULL,
  order_id uuid REFERENCES public."order"(id) ON DELETE SET NULL,
  sku_id bigint REFERENCES public.sku(id) ON DELETE SET NULL,
  price numeric(10,5),
  mianliao_bianhao text
);

ALTER TABLE public.order_sku_detail ENABLE ROW LEVEL SECURITY;
